name: Build

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "Version"

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'windows-latest'
            args: ''
            denoUrl: 'https://github.com/denoland/deno/releases/latest/download/deno-x86_64-pc-windows-msvc.zip'
            ytdlpUrl: 'https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp.exe'
            denoName: 'deno-x86_64-pc-windows-msvc.exe'
            ytdlpName: 'yt-dlp-x86_64-pc-windows-msvc.exe'
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            denoUrl: 'https://github.com/denoland/deno/releases/latest/download/deno-aarch64-apple-darwin.zip'
            ytdlpUrl: 'https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download/yt-dlp_macos'
            denoName: 'deno-aarch64-apple-darwin'
            ytdlpName: 'yt-dlp-aarch64-apple-darwin'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin' || '' }}
      
      - name: install dependencies
        run: |
          bun install
      
      - name: download deno
        shell: bash
        run: |
          mkdir -p src-tauri/binaries
          curl -fsSL ${{ matrix.denoUrl }} -o deno.zip
          unzip deno.zip
          mv deno src-tauri/binaries/${{ matrix.denoName }}
      
      - name: download yt-dlp
        shell: bash
        run: |
          mkdir -p src-tauri/binaries
          curl -fsSL ${{ matrix.ytdlpUrl }} -o ytdlp
          mv ytdlp src-tauri/binaries/${{ matrix.ytdlpName }}
      
      - name: permission
        if: ${{ matrix.platform == 'macos-latest' }}
        run: |
          chmod +x src-tauri/binaries/${{ matrix.denoName }}
          chmod +x src-tauri/binaries/${{ matrix.ytdlpName }}
          xattr -d com.apple.quarantine src-tauri/binaries/${{ matrix.denoName }} || true
          xattr -d com.apple.quarantine src-tauri/binaries/${{ matrix.ytdlpName }} || true

      - name: build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.event.inputs.version || github.ref_name }}
          releaseName: ${{ github.event.inputs.version || github.ref_name }}
          releaseBody: ''
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}